# Generated by Django 4.1.3 on 2022-12-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_personne_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='recipes.personne'),
        ),
    ]
