# Generated by Django 4.1.3 on 2022-12-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_reservation_personne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='personne',
            new_name='user',
        ),
    ]
